### ISSUE TITLE
Support for Android.

### ISSUE THREAD

**Issue by piospy** [google/certificate-transparency-java#25]
Are there any plans to create an android specific version of this library or it should be used as it is in android app?
Do you know if there are any plans to support Certificate Transparency in android SDK as it is in iOS?
I'm also worried if the library is mature enough to be used in the production android app since I can see that the version number of this library is 0.1.3.
Would you recommend to use ssl pinning in android app until the Certificate Transparency is officially supported in Android?

**Comment by rivercartwright** [comment]
I am not affiliated with this project, however, I have been reading and experimenting with this code recently. I have compiled a list of things that I would do if I were told I had to produce a version of this for Android.
* Refactor into two separate jars so that the classes that uses the Apache HTTP components are in a client focused jar and the rest of the code is in a core jar. The Apache HTTP components conflict with the Android network classes.
* Replaces uses of BouncyCastle with SpongyCastle which is the preferred BC implementation.
* Replace use of com.google-code.json-simple with Gson, which contains newer bytecode which is compatible with Android.

**Comment by rivercartwright** [comment]
I have published a variant of this repository that is compatible with Android for my purposes.
https://github.com/anonyome/certificate-transparency-android

**Comment by mattmook** [comment]
I work at Babylon Health where we have recently open sourced our own Android version of this which we have been working on since the end of 2018 at https://github.com/Babylonpartners/certificate-transparency-android

We have set it up with easy configuration for use with OkHttp, HttpUrlConnection and Volley, you specify the domains you want CT to be enforced with and the library takes care of everything else, such as getting hold of an up-to-date log list.

**Comment by RJPercival** [comment]
Thank you for creating these variants for supporting Android. We don't have any plans to add support to this repository but we'll document this in the README and link to your repositories.
