### ISSUE TITLE
Code quality: Run google-java-format, style guide compliance

### ISSUE THREAD

**Issue by codingllama** [google/certificate-transparency-java#8]
Links:
https://github.com/google/google-java-format
https://google.github.io/styleguide/javaguide.html

**Comment by codingllama** [comment]
I'm happy to take the formatting changes in a single batch. I actually prefer it that way, instead of broken down into multiple PRs.

I'd like to have google-java-format running as part of the build, as you suggested, but I haven't looked into how much trouble it is. In any case, having an easy way to run it, even if it's manual, beats what we have now. There isn't a lot of dev going on in this repo, so the code should remain relatively stable.

**Comment by tigertoes** [comment]
With regards to fixing this as part of the build process, I see a few options:
* Provide a maven plugin to google-java-format, which would resolve google/google-java-format#69
* Use Coveo's [maven plugin](https://github.com/coveo/fmt-maven-plugin), it's MIT licensed (which appears on the [notice list](https://opensource.google.com/docs/thirdparty/licenses/#list) for Google's approved licenses).
* Look at switching over to Bazel instead of Maven - Gerrit has [incorporated the java formatter](https://gerrit-review.googlesource.com/#/c/100691/) as part of their build process. I'm completely unfamiliar with Bazel, so this to me appears the most difficult.
* There could be other tooling inside of Google I'm not privvy to that may also be considered for open sourcing.

I'm leaning towards using Coveo's tooling for now, as it exists and appears to work and I think I can manipulate it to be incorporated during the compile phase. Any thoughts @codingllama?

**Comment by codingllama** [comment]
fmt-maven-plugin seems to be the way to go. No reason to write our own, nor is this a strong enough reason to change build systems IMO.

**Comment by tigertoes** [comment]
I guess we can close this ticket?

**Comment by codingllama** [comment]
We're well covered on the google-java-format part. Thanks for contributing it!

There may be more to be done on style guide compliance, but I'm happy enough to have the ticket closed.
